#!/bin/bash

today_year=$(date "+%Y")

echo -n "Enter year (default: $today_year): "
read year

if [ -z "$year" ]; then
	year=$today_year
fi

today=$(date "+%d")

echo -n "Enter day (default: $today): "
read day

if [ -z "$day" ]; then
	day=$today
fi

code="src/bin/${year}_$day.rs"

if [ -e "$code" ]; then
	echo "File already exists, if you want to overwrite it go edit this script and remove the check"
	exit 1
fi

cat template.rs <(echo -e "\nday!($year $day);") > "$code"
