#!/bin/bash

echo -n "Enter year: "
read year
echo -n "Enter day: "
read day

code="src/bin/${year}_$day.rs"
input="$year/$day"

if [ -e "$code" ]; then
	echo "File already exists, if you want to overwrite it go edit this script and remove the check"
	exit 1
fi

sed 's!{{NAME}}!'"$input"'!g' template > "$code"
